name: flake8-pytest

on:
 - push
 - pull_request

jobs:
  flake8-pytest:
    runs-on: ubuntu-latest
    steps:
 - uses: actions/checkout@v2
 - name: linter
        run: |
 pip install poetry
 make install
 - name: Run linter
        run: |
 make lint
